// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpelvqsfzafbqambomtx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wZWx2cXNmemFmYnFhbWJvbXR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzMTYxMzYsImV4cCI6MjA0OTg5MjEzNn0.imkaxmMlSXlyGhPFZMLKW-fzr_W71JnB5uEMkXRNDp8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);